#! /bin/bash

# Needs to be passed the version number as an argument!
[[ $1 ]] || exit

echo "Working..."

# Paths for syncing
path="/home/colin/code/aur/aura-bin"
aura="/home/colin/code/haskell/aura"

# Files to copy from the current Aura source
news=("$aura/LICENSE"
      "$aura/pkg/aura/usr/bin/aura"
      "$aura/doc/aura.8"
      "$aura/doc/completions/bashcompletion.sh"
      "$aura/doc/completions/_aura")

# Files to delete before copying
olds=("LICENSE"
      "aura"
      "aura.8"
      "bashcompletion.sh"
      "_aura")

# Remove old versions
echo "Removing olds files..."
rm ${olds[@]}

# Remove build/source tarballs
echo "Removing old tarballs..."
rm aura-*

# Sync new versions
echo "Copy new files..."
for n in ${news[@]}; do
    cp $n $path
done

# Create x86_64 tarball
tar -czf aura-$1-x86_64.tar.gz ${olds[@]}
makepkg -g

# Create i686 tarball
# rm aura
# cp ?? $path  # Need to compile the i686 version ahead of time.
# tar -czf aura-$1-i686.tar.gz ${olds[@]}
# makepkg -g   # Wait, what?

# makepkg --source

echo "Done."
